###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nautilus
$menu = rofi
$browser = firefox
$user = thiago_lins
$HOME = /home/$USER
$steam = env LD_PRELOAD=/usr/lib32/libextest.so mangohud /usr/bin/steam
$whatsApp = env QT_STYLE_OVERRIDE=breeze zapzap
$hyprshell = hyprshell run
$mail = GDK_BACKEND=x11 evolution

################
### SERVICES ###
################

exec-once = qs -c noctalia-shell &
exec-once = hyprpm reload &
exec-once = hypridle &
exec-once = sway-audio-idle-inhibit &
exec-once = $hyprshell &
exec-once = kdeconnectd &
exec-once = sleep 5 && easyeffects -w
exec-once = sleep 5 && openrgb -p Default --startminimzed
exec-once = sleep 5 && flameshot
exec-once = sleep 5 && hyprctl setcursor $cursorTheme 1
exec-once = sleep 5 && sway-audio-idle-inhibit

#################
### AUTOSTART ###
#################

exec-once = [workspace 3 silent] sleep 5 && discord
exec-once = [workspace 3 silent] spotify-launcher
exec-once = [workspace 2 silent] $mail
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] $whatsApp
exec-once = [workspace 4 silent] $steam
