local themes = require("settings.themes")
local apps = require("settings.applications")

hl.on("hyprland.start", function()
	hl.exec_cmd("hyprctl setcursor " .. themes.cursor .. " 1 &")
	hl.exec_cmd("hyprpm reload &")
	hl.exec_cmd(apps.services.shell .. " &")
	hl.exec_cmd(apps.services.idle_inhibit .. " &")
	hl.exec_cmd(apps.services.window_switcher .. " &")
	hl.exec_cmd("sleep 5 && " .. apps.services.kde_connect .. " &")
	hl.exec_cmd("sleep 5 && " .. apps.services.easy_effects)
	hl.exec_cmd("sleep 5 && " .. apps.services.openrgb)
	hl.exec_cmd(apps.services.screenshot)

	hl.exec_cmd("[workspace 4 silent] " .. apps.steam)
	hl.exec_cmd("[workspace 3 silent] sleep 5 && " .. apps.discord)
	hl.exec_cmd("[workspace 3 silent] " .. apps.spotify)
	hl.exec_cmd("[workspace 2 silent] " .. apps.browser)
	hl.exec_cmd("[workspace 2 silent] " .. apps.mail)
end)
